### PR TITLE
Add ignore field support

### LINKED ISSUE #5: Support ignore field count
The `-f` flag

### PR DESCRIPTION
**Pull request by K0UR05H**
Closes #5

### CODE REVIEW

**Comment by JakeWharton** [comment]
Needs rebased and updated to use new config. I can do it tomorrow unless you get to it first.

Thanks for all this work!

**Comment by JakeWharton** [comment]
Also we should probably throw a test in now that you've set me up with those!

**Comment by K0UR05H** [comment]
Definitely! I'll make the changes.

**Comment by JakeWharton** [comment]
Great stuff!

**Pull request merged**
